name: Premier League Bot

on:
  schedule:
    # Run every 2 hours (GitHub Actions uses UTC time)
    - cron: "0 */2 * * *"

  # Allow manual triggering from GitHub Actions tab
  workflow_dispatch:

jobs:
  generate-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google client secret to file
        run: |
          cat <<EOF > client_secret_183380586106-us149j4ocu1jmgekv7f24dd12ai2f75n.apps.googleusercontent.com.json
${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
EOF

      - name: Run article generation
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          OWNER_CHAT_ID: ${{ secrets.OWNER_CHAT_ID }}
          REVIEW_TIMEOUT_MINUTES: 5
        run: python github_actions_main.py
